In [3]:
# comparison of vectorization and explicit for-loop way

import numpy as np
import time
import math

n = 1000000
u = np.zeros((n,1))
v = np.zeros((n,1))

tic = time.time()
for i in range(n):
    u[i] = math.exp(v[i])
toc = time.time()
print('time:', toc-tic)
    
tic = time.time()
u = np.exp(v)
toc = time.time()
print('time:', toc-tic)


time: 1.1066350936889648
time: 0.020469188690185547


In [ ]:
# Logist regression derivatives
import numpy as np

dw = np.zeros(n-x,1)
dw = np.dot(x, dz)

# z = w' * X
z = np.dot(w.T, x) + b
A = simga(z)
dz = A - Y
dw = 1/m*X*dz.T
db = 1/m*np.sum(dz)

# update w, b by learning rate alpha
w -= alpha*dw
b -= alpha*db

In [15]:
# demo of broadcasting
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([4, 5, 6])
print(x+y)
z = np.array([[100], [200]])
print(x+z)

[[ 5  7  9]
 [ 8 10 12]]
[[101 102 103]
 [204 205 206]]


In [26]:
# numpy quick demo

# notice (5,) and (5,1)
a = np.random.randn(5) # don't use
print(a)
print(a.shape)
print(a.T)
print('np.dot(a,a.T)', np.dot(a,a.T))

a = np.random.randn(5,1) # recommand
print('a', a)
print('np.dot(a,a.T): ',np.dot(a,a.T))

assert(a.shape==(5,1))
assert(a.shape==(5,))

[ 1.1415527   1.27671108  0.26310593  1.04267236 -0.56249379]
(5,)
[ 1.1415527   1.27671108  0.26310593  1.04267236 -0.56249379]
np.dot(a,a.T) 4.40592340618
a [[-0.13303431]
 [ 2.0640228 ]
 [-1.80975265]
 [-0.40918547]
 [ 0.16943733]]
np.dot(a,a.T):  [[ 0.01769813 -0.27458586  0.2407592   0.05443571 -0.02254098]
 [-0.27458586  4.26019011 -3.73537074 -0.84456813  0.34972251]
 [ 0.2407592  -3.73537074  3.27520467  0.74052449 -0.30663966]
 [ 0.05443571 -0.84456813  0.74052449  0.16743275 -0.06933129]
 [-0.02254098  0.34972251 -0.30663966 -0.06933129  0.02870901]]


AssertionError: 