# Lecture 2 Tensorflow operation


## 1 Visualize with TensorBoard

In [3]:
import tensorflow as tf
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs', sess.graph)
	print(sess.run(x))
writer.close() # close the writer when you're done using it.

5


 Bash command (to view tensorboard):
 
 ```bash
 tensorboard --logdir='./graphs' --port 6006
 open http://localhost:6006/#graphs
 ```
 
 ### Explicity name operation, variable


In [4]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a,b,name='add')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs', sess.graph)
	print(sess.run(x))
writer.close() # close the writer when you're done using it.

5


The figure produced by TensorBoard is as follows:

![](images/explicit_name.png)

**Note**:  Learn to use TensorBoard well and often. It will help a lot when you build complicated models.

## 2 Constant types

### Tensors filled with a specific value


Using `tensorflow.zeros` to fill tensor with zeors, which is similar to `Numpy`:

```python
tf.zeros(shape, dtype=tf.float32, name=None)
```

For example,

In [6]:
x = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(x))

[[0 0 0]
 [0 0 0]]


`tensorflow.zeros_like` return an tensor of zeros with the same shape and type as a given tensor. For example, we may want to have a tensor filled with zeros, with the same shape as `x`:

In [9]:
y = tf.zeros_like(x)
with tf.Session() as sess:
    print(sess.run(y))

[[0 0 0]
 [0 0 0]]


There are other command to fill tensor with a specific value, such as `tensorflow.ones`, `tensorflow.ones_like`, which of usuage is similar to `tensorflow.zeros`,`tensorflow.zeros_like`.

`tensorflow.fill` creates a tensor filled with a scalar value:
```python
tf.fill(dims, value, name=None)
```

In [10]:
z = tf.fill([3,4],3)
with tf.Session() as sess:
    print(sess.run(z))

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


### Constants as sequences

You can create constants that are sequences, using `tf.linspace`, `tf.range`:

```python
tf.linspace(start, stop, num, name=None)

# create a sequence of num evenly-spaced values are generated beginning at  start. If num > 1, the values in the sequence increase by stop - start / num - 1, so that the last one is exactly stop.
# start, stop, num must be scalars
# comparable to but slightly different from numpy.linspace
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

tf.range(start, limit=None, delta=1, dtype=None, name='range')
# create a sequence of numbers that begins at start and extends by increments of delta up to but not including limit
# slight different from range in Python
```

In [18]:
x = tf.linspace(10.0, 13.0, 4, name='linspace')
y = tf.range(3, 18)
z= tf.range(3, 18, 3)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))

[ 10.  11.  12.  13.]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 3  6  9 12 15]


## 3 Math Operations

![](images/math_operations.png)

In [35]:
a = tf.constant([[3,6],[0,0]])
b = tf.constant([[0,0],[2,2]])
x1 = tf.add(a, b)
x2 = tf.add_n([a,b,b]) # >> [7 10]. Equivalent to a + b + b
x3 = tf.multiply(a, b) # >> [6 12] because mul is element wise
x4 = tf.matmul(a, b) # >> ValueError
x5 = tf.matmul(tf.reshape(a, [4, 1]), tf.reshape(b, [1, 4])) # >> [[18]]

with tf.Session() as sess:
    sess.run(a)
    sess.run(b)
    print('x1:\n', sess.run(x1))
    print('x2:\n', sess.run(x2))
    print('x3:\n', sess.run(x3))
    print('x4:\n', sess.run(x4))
    print('x5:\n', sess.run(x5))

x1:
 [[3 6]
 [2 2]]
x2:
 [[3 6]
 [4 4]]
x3:
 [[0 0]
 [0 0]]
x4:
 [[12 12]
 [ 0  0]]
x5:
 [[ 0  0  6  6]
 [ 0  0 12 12]
 [ 0  0  0  0]
 [ 0  0  0  0]]


## 4 TensorFlow data types:


### Python Native Types

TensorFlow takes Python natives types: `boolean`, `numeric` (`int`, `float`), `strings`

TensorFlow takes in Python native types such as Python boolean values, numeric values (integers, floats), and strings. Single values will be converted to 0-d tensors (or scalars), lists of values will be converted to 1-d tensors (vectors), lists of lists of values will be converted to 2-d tensors (matrices), and so on.


In [49]:
tf.InteractiveSession() # open tensorflow interactivesession
t_0 = 19   # Treated as a 0-d tensor, or "scalar" 
print('t_0:',t_0)
print(tf.zeros_like(t_0))   # ==> 0
print(tf.ones_like(t_0))   # ==> 1
t_1 = [b"apple" ,  b"peach" ,  b"grape"]   # treated as a 1-d tensor, or "vector" 
print('t_1:',t_1)
print(tf.zeros_like(t_1))   # ==> ['' '' '']
t_2= [[ True, False, False],  [False, False, True], [False, True ,   False ]]   # treated as a 2-d tensor, or "matrix"
print('t_2:',t_2)
print(tf.zeros_like(t_2))   # ==> 2x2 tensor, all elements are False 
print(tf.ones_like(t_2))   # ==> 2x2 tensor, all elements are True

t_0: 19
Tensor("zeros_like_32:0", shape=(), dtype=int32)
Tensor("ones_like_20:0", shape=(), dtype=int32)
t_1: [b'apple', b'peach', b'grape']
Tensor("zeros_like_33:0", shape=(3,), dtype=string)
t_2: [[True, False, False], [False, False, True], [False, True, False]]
Tensor("zeros_like_34:0", shape=(3, 3), dtype=bool)
Tensor("ones_like_21:0", shape=(3, 3), dtype=bool)


**Note: Do not use Python native types for tensors because TensorFlow has to infer Python type.**

### TensorFlow Native Types

Like `NumPy`, `TensorFlow` also its own data types such as `tf.int32`, `tf.float32`. Below is a list of current TensorFlow data types.

![](images/tensorflow_data_types.png)

### Numpy Data Types

By now, you’ve probably noticed the similarity between `NumPy` and `TensorFlow`. `TensorFlow` was designed to integrate seamlessly with `Numpy`, the package that has become the  lingua franca of data science.

TensorFlow’s data types are based on those of NumPy; in fact, `np.int32 == tf.int32` returns `True`. You can pass `NumPy` types to `TensorFlow` ops.


Example:

In [52]:
import numpy as np
tf.ones([2, 2],  np.float32)

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [57]:
x = np.zeros((2,2))
tf.ones_like(x)

<tf.Tensor 'ones_like_22:0' shape=(2, 2) dtype=float64>

### Constant

Constants are stored in the graph definition. This makes loading graphs expensive when constants are big. **Only use constants for primitive types, use variables or readers for more data that requires more memory**.


In [62]:
g = tf.Graph() # to add operators to a graph, set it as default:
with g.as_default():
    my_const = tf.constant([1.0, 2.0], name="my_const")
    with tf.Session() as sess:
        print(sess.graph.as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\200?\000\000\000@"
      }
    }
  }
}
versions {
  producer: 24
}



### Variables

`tf.constant` is an operation, but `tf.Variable` is a class. `tf.Variables` holds several operations:

In [95]:
tf.InteractiveSession()
xx = tf.Variable(23, name='scalar')
xx.initializer # init op
xx.value() # read op
assign_op = xx.assign(5)


You have to initilize `variables`, The easiest way is initializing all variables at once:

In [97]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(xx.eval())
    sess.run(assign_op)
    print(xx.eval())

23
5


#### Each session maintains its own copy of variable

In [100]:
W = tf.Variable(10, name='W')
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2))) # not 18!

sess1.close()
sess2.close()

20
8


#### Use a variable to initialize another variable

In [109]:
# want to declare U = 2*W
# W is random tesnor
W = tf.Variable(tf.truncated_normal([4, 2]))
U = tf.Variable(2*W.initialized_value())
with tf.Session() as sess:
    sess.run(U.initializer)
    print(U.eval())

[[ 1.11442947 -3.1675539 ]
 [ 3.02267933 -0.81786388]
 [ 2.57613969 -0.98440802]
 [ 0.6298722  -0.38194153]]


#### Session vs InteractiveSession,

You sometims see InteractiveSession instead of Session. The only difference is an InteractiveSession makes itself the default.


In [110]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a*b
# We can just use `c.eval()` with out specifying the context `sess`
print(c.eval())
sess.close()

30.0


### Placeholder

A TensorFlow program often has 2 phases:

1. Assemble a graph
2. Use a session to execute operations in the graph

$\rightarrow$ can assemble the graph without knowing the values needed for computation

**Analogy**: Can define the function $f(x,y) = x*2+y$ without knowing value of $x$ or $y$.

So using `placeholders`, we can later supply their data when they needed to execute the computation.

```
tf.placeholder(dtype, shape=None, name=None_
```

`shape=None` means that tensor of nay shape will be accepted as value for placeholder. `shape=None` is easy to constrcut graphs, but nighmarish for debugging.

### Lazy loading

`Lazy loading` means defer creating/initialzing an object until it is needed.


Normal loading:

In [129]:
g = tf.Graph()
with g.as_default():
    x = tf.Variable(10, name='x')
    y = tf.Variable(20, name='y')
    z = tf.add(x,y) # you create the node for add node befre executing the graph

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for _ in range(10):
            sess.run(z)


Lazy loading:

In [128]:
g = tf.Graph()
with g.as_default():
    x = tf.Variable(10, name='x')
    y = tf.Variable(20, name='y')

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        writer = tf.summary.FileWriter('./my_graph/12', sess.graph)
        for _ in range(10):
            sess.run(tf.add(x,y)) # someone decides to be clever to save one line of code
        writer.close()

Note: In Lazy loading, Node `ADD` added 10 times to the graph definition. Image you want to compute an operations thousands of times, you graph gets bloated slow to load, and expensive to pass around.

**Solution**: 

1. Separate definition of ops from computing/running ops
2. Use Python property to ensure function is also loaded once the first time it is called.
